name: generate portfolio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate portfolio
      run: |
        python generate.py
        
    - name: Commit files  # transfer the new html files back into the repository
      run: |
          git config --local user.name  ${{ github.actor }}
          git add index.html
          git commit -m "Updating index.html"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          
